### ISSUE TITLE
Representative weeks potential bug

### ISSUE THREAD

**Issue by sericson-epri** [IIT-EnergySystemModels/openTEPES#62]
Hello all,
Thank you for your time and effort on this project. I wanted to reach out regarding the temporal aggregation for representative weeks. 

I was testing with a simple case study with a single demand node with flat demand and a single generator and am getting very different results with and without the representative weeks. See the attached zip file for the testing (the hourly folder contains the duration and stage files to run every hour and the agg contains the files to run for representative weeks) 
[test.zip](https://github.com/user-attachments/files/16428859/test.zip)

Here are the hourly results, 
![image](https://github.com/user-attachments/assets/7c8f02e5-d77f-4e2b-84c7-bce54e7ce975)

and here are the results if i replace Duration, Data_Stage, and Dict_Stage with the representative week values keeping all other files the same
![image](https://github.com/user-attachments/assets/ff82ea28-eceb-4f90-9d52-6bed072bc981)

I am also getting the following warning for each of the 13 stages when running with representative weeks. 

![image](https://github.com/user-attachments/assets/e55bbdc3-8e55-4be4-bb54-36a14a903fea)

If it is helpful, I am using a gams solver for the model. 
Any help debugging would be much appreciated, and apologies in advance if it is a simple user error on my end

**Comment by erikfilias** [comment]
Hi @sericson-epri,

Thank you for reporting the differences.
Indeed, there was an issue in the model building.
I just fixed it and distributed the model via Pypi in a pre-release: https://pypi.org/project/openTEPES/4.17.5rc1/
Download it or clone the current repository version for running the model again.

In addition, I fixed another small issue regarding your test case in the OutputResults.
The figure below shows that the model is running well, considering your test case with 13 representative weeks. 
Please check it again and let us know if there is another issue.
![image](https://github.com/user-attachments/assets/3ebfc82b-8597-40dc-ab56-6eddaabee0fe)

Regarding the CSV related to the cost summary (and the summary cost in the Prompt), I found another small issue since it shows only the results of the last representative period.
We are on summer vacation, but we will try to fix it asap.

cc. @arght

**Comment by arght** [comment]
Hi @sericson-epri
I think that I have solved the issue. Now the problem solved by stages and hourly gives the same results. The new version is updated in GitHub.
Let us know if anything else fails
Regards
Andrés

cc: @erikfilias

**Comment by sericson-epri** [comment]
Thank you so much for looking into this, and very much appreciate the support!
